### Post person
POST http://localhost:3001/api/persons/
Content-Type: application/json

{
    "name": "Bob Barley",
    "number": "44-13123-123"
}

### Post another peroson
POST http://localhost:3001/api/persons/
Content-Type: application/json

{
    "name": "Albert Einstein",
    "number": "543-123-53"
}

### Post person with number missing
POST http://localhost:3001/api/persons/
Content-Type: application/json

{
    "name": "Albert Einstein"
}

### Post person with name missing
POST http://localhost:3001/api/persons/
Content-Type: application/json

{
    "number": "543-123-53"
}